support smaller overrides

diff --git a/overrides/mount- b/overrides/mount-
--- a/overrides/mount-
+++ b/overrides/mount-
@@ -1,17 +1,17 @@
 # notes:
 # - this technically targets mount-1003.1-2008
 
-execers(){
-	cat > $out/execers
-} <<EOF
-cannot${drv}/bin/mount
-EOF
+# $1 = verdict
+# $2 = executable
+execer(){
+	case "$2" in
+		mount)
+			printf "cannot"
+			;;
+		*)
+			echo error, bill bobbinson! 1>&2
+			exit 2
+			;;
+	esac
+}
 
-wrappers(){
-	cat > $out/wrappers
-} <<EOF
-EOF
-
-for type in "$@"; do
-	$type
-done
diff --git a/overrides/procps- b/overrides/procps-
--- a/overrides/procps-
+++ b/overrides/procps-
@@ -1,17 +1,15 @@
 # notes:
 
-execers(){
-	cat > $out/execers
-} <<EOF
-cannot${drv}/bin/ps
-cannot${drv}/bin/top
-EOF
-
-wrappers(){
-	cat > $out/wrappers
-} <<EOF
-EOF
-
-for type in "$@"; do
-	$type
-done
+# $1 = verdict
+# $2 = executable
+execer(){
+	case "$2" in
+		ps|top)
+			printf "cannot"
+			;;
+		*)
+			echo error, bill bobbinson! 1>&2
+			exit 2
+			;;
+	esac
+}
diff --git a/overrides/ps- b/overrides/ps-
--- a/overrides/ps-
+++ b/overrides/ps-
@@ -1,17 +1,16 @@
 # notes:
 # - this technically targets ps-1003.1-2008, but the real "goal" is procps ps which will also manifest as ps depending on platform and how it's specified
 
-execers(){
-	cat > $out/execers
-} <<EOF
-cannot${drv}/bin/ps
-EOF
-
-wrappers(){
-	cat > $out/wrappers
-} <<EOF
-EOF
-
-for type in "$@"; do
-	$type
-done
+# $1 = verdict
+# $2 = executable
+execer(){
+	case "$2" in
+		ps)
+			printf "cannot"
+			;;
+		*)
+			echo error, bill bobbinson! 1>&2
+			exit 2
+			;;
+	esac
+}
diff --git a/overrides/top- b/overrides/top-
--- a/overrides/top-
+++ b/overrides/top-
@@ -1,17 +1,17 @@
 # notes:
 # - this technically targets top-1003.1-2008, but the real "goal" is procps top which will also manifest as unixtools.top depending on platform and how it's specified
 
-execers(){
-	cat > $out/execers
-} <<EOF
-cannot${drv}/bin/top
-EOF
+# $1 = verdict
+# $2 = executable
+execer(){
+	case "$2" in
+		top)
+			printf "cannot"
+			;;
+		*)
+			echo error, bill bobbinson! 1>&2
+			exit 2
+			;;
+	esac
+}
 
-wrappers(){
-	cat > $out/wrappers
-} <<EOF
-EOF
-
-for type in "$@"; do
-	$type
-done
